version: '3'
services:
  aboyon:
    container_name: aboyon
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rackup --host 0.0.0.0 -p 4567
    volumes:
      - .:/app:cached
    ports:
      - "4567:4567"
    env_file: .env
